version: '3.3'

volumes:
  postgres_data:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=123qwe
      - POSTGRES_USER=app
      - POSTGRES_DB=users
    ports:
      - "5432:5432"

  auth_app:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - ./.env
    ports:
      - "8008:8008"

  test:
    build:
      context: ./src/tests
      dockerfile: Dockerfile
    entrypoint: >
      sh -c "cd functional && pytest"
    depends_on:
      - auth_app