version: '3.3'

volumes:
  postgres_data:

services:
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf

  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=123qwe
      - POSTGRES_USER=app
      - POSTGRES_DB=users
    ports:
      - "5432:5432"

  auth_app:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - ./.env
    ports:
      - "8008:8008"

  nginx:
      image: nginx:latest
      volumes:
        - ./nginx/etc/nginx/conf.d:/etc/nginx/conf.d
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - auth_app
      ports:
        - "80:80"