"""Social network

Revision ID: cdc5b0f662f5
Revises: da6547b571a9
Create Date: 2022-06-05 13:00:28.515327

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'cdc5b0f662f5'
down_revision = 'da6547b571a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'social', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'social', type_='unique')
    # ### end Alembic commands ###
