version: '3.3'


services:

  auth_app:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - ./.env
    expose:
      - "8008"

  nginx:
      image: nginx:latest
      volumes:
        - ./nginx/etc/nginx/conf.d:/etc/nginx/conf.d
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - auth_app
      ports:
        - "80:80"