swagger: "2.0"
info:
  version: "1.0.0"
  title: "Registration, authorization, identification"
basePath: "/api/v1"
tags:
  - name: "Hz"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /register:
    post:
      tags:
        - "Registration"
      summary: "You can register here"
      operationId: register
      parameters:
        - name: "body"
          in: "body"
          description: "email, first_name, second_name, login, password"
          required: true
          schema:
            $ref: "#/definitions/Person"
      responses:
        201:
          description: "You registered successfully"
        400:
          description: "User already exists"
      x-swagger-router-controller: "app.api.v1.registration"
  /role:
    post:
      tags:
        - "CRUD"
      summary: "Create a role"
      operationId: create_role
      parameters:
        - name: "body"
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/Role"
      responses:
        201:
          description: "Role created"
        400:
          description: "Role already exists"
      x-swagger-router-controller: "app.api.v1.role"
  /role/{role_id}:
    put:
      tags:
        - "CRUD"
      summary: "Change a role"
      operationId: change_role
      parameters:
        - name: "role_id"
          in: "path"
          required: true
          type: "string"
        - name: "body"
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/Role"
      responses:
        200:
          description: "Role changed"
        400:
          description: "Cannot change this role or Role already exists"
        404:
          description: "No such role"
      x-swagger-router-controller: "app.api.v1.role"
    delete:
      tags:
        - "CRUD"
      summary: "Delete a role"
      operationId: delete_role
      parameters:
        - name: "role_id"
          in: "path"
          required: true
          type: "string"
      responses:
        200:
          description: "Role deleted"
        400:
          description: "Cannot delete this role"
        404:
          description: "No such role"
      x-swagger-router-controller: "app.api.v1.role"
  /role/{user_id}/{role_id}:
    post:
      tags:
        - "CRUD"
      summary: "Give a role"
      operationId: give_role
      parameters:
        - name: "user_id"
          in: "path"
          required: true
          type: "string"
        - name: "role_id"
          in: "path"
          required: true
          type: "string"
      responses:
        201:
          description: "Role is given"
        400:
          description: "User already has this role"
        404:
          description: "No such role or user"
      x-swagger-router-controller: "app.api.v1.role"
    delete:
      tags:
        - "CRUD"
      summary: "Take a role"
      operationId: take_role
      parameters:
        - name: "user_id"
          in: "path"
          required: true
          type: "string"
        - name: "role_id"
          in: "path"
          required: true
          type: "string"
      responses:
        200:
          description: "Role was taken"
        400:
          description: "No such role or user"
      x-swagger-router-controller: "app.api.v1.role"

  
definitions:
  Role:
    type: "object"
    required:
      - "name"
      - "description"
    properties:
      name:
        type: "string"
      descriptions:
        type: "string"
    example:
      name: "user"
      description: "Cool role"
  Person:
    type: "object"
    required:
      - "first_name"
      - "second_name"
      - "login"
      - "email"
      - "password"
    properties:
      id:
        type: "string"
      first_name:
        type: "string"
      second_name:
        type: "string"
      login:
        type: "string"
      email:
        type: "string"
        format: "email"
      password:
        type: "string"
        format: "password"
    example:
      first_name: "Ivan"
      second_name: "Ivanov"
      login: 'vanka'
      email: "ivan500@gmail.com"
      password: "SuperVanya228!"