# Generated by Django 3.2 on 2022-02-05 23:43

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filmwork',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='timestamp.created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='timestamp.modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='film_work.name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='film_work.description')),
                ('creation_date', models.DateField(blank=True, null=True, verbose_name='film_work.creation_date')),
                ('rating', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='film_work.rating')),
                ('type', models.CharField(choices=[('movie', 'film_work.typechoices.movie'), ('tv_show', 'film_work.typechoices.tv_show')], default='movie', max_length=7, verbose_name='film_work.type')),
                ('certificate', models.CharField(blank=True, max_length=512, null=True, verbose_name='film_work.certificate')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='movies/', verbose_name='film_work.file')),
            ],
            options={
                'verbose_name': 'film_work.meta.verbose_name',
                'verbose_name_plural': 'film_work.meta.verbose_name_plural',
                'db_table': 'content"."film_work',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='timestamp.created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='timestamp.modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='genre.name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='genre.description')),
            ],
            options={
                'verbose_name': 'genre.meta.verbose_name',
                'verbose_name_plural': 'genre.meta.verbose_name_plural',
                'db_table': 'content"."genre',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='timestamp.created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='timestamp.modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, verbose_name='person.full_name')),
                ('birth_date', models.DateField(blank=True, default=None, null=True, verbose_name='person.birth_date')),
            ],
            options={
                'verbose_name': 'person.meta.verbose_name',
                'verbose_name_plural': 'person.meta.verbose_name_plural',
                'db_table': 'content"."person',
            },
        ),
        migrations.CreateModel(
            name='PersonFilmwork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(max_length=512, null=True, verbose_name='Роль')),
                ('film_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.filmwork')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.person')),
            ],
            options={
                'verbose_name': 'person_film_work.meta.verbose_name',
                'verbose_name_plural': 'person_film_work.meta.verbose_name_plural',
                'db_table': 'content"."person_film_work',
                'unique_together': {('film_work', 'person', 'role')},
            },
        ),
        migrations.CreateModel(
            name='GenreFilmwork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('film_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.filmwork')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.genre')),
            ],
            options={
                'verbose_name': 'genre_film_work.meta.verbose_name',
                'verbose_name_plural': 'genre_film_work.meta.verbose_name_plural',
                'db_table': 'content"."genre_film_work',
                'unique_together': {('film_work', 'genre')},
            },
        ),
        migrations.AddField(
            model_name='filmwork',
            name='genres',
            field=models.ManyToManyField(through='movies.GenreFilmwork', to='movies.Genre'),
        ),
        migrations.AddField(
            model_name='filmwork',
            name='persons',
            field=models.ManyToManyField(through='movies.PersonFilmwork', to='movies.Person'),
        ),
    ]
