"""User password nullable

Revision ID: da6547b571a9
Revises: ae114bd3e9db
Create Date: 2022-06-04 17:23:41.492210

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'da6547b571a9'
down_revision = 'ae114bd3e9db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
